/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package inventory_barang;
import java.sql.SQLException;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.Statement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Denny
 */
public class Inventory_Barang extends javax.swing.JFrame {
private Connection con; 
private Statement stat; 
private ResultSet res;
    /**
     * Creates new form Inventory_Barang
     */
    public Inventory_Barang() {
        initComponents();
        setTitle("Inventory Barang");
        koneksi();
        tabel1();
        tabel2();
        //membuat layout tampil di tengah pada saat di tampilkan
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        Dimension frameSize = getSize();
        setLocation(
        (screenSize.width - frameSize.width) / 2,
        (screenSize.height - frameSize.height) / 2);
    }
 private void koneksi() 
{ try 
{ 
Class.forName("com.mysql.jdbc.Driver"); con=DriverManager.getConnection("jdbc:mysql://localhost:3306/inventory_barang", "root", ""); 
stat=con.createStatement(); 
} catch (ClassNotFoundException | SQLException e) { 
JOptionPane.showMessageDialog(null, e); 
} }

private void kosongkan()
{ 
kode.setText(""); 
nama.setText("");
tglm.setText("");
tglk.setText(""); 
jumlah.setText("");
kondisi.setSelectedIndex(-1); 
kode.requestFocus();
 }
 
private void tabel1(){ 
DefaultTableModel t= new DefaultTableModel();
t.addColumn("Kode Barang"); 
t.addColumn("Nama Barang");
t.addColumn("Tanggal Masuk"); 
t.addColumn("Jumlah"); 
t.addColumn("Kondisi"); 
 tbl1.setModel(t); try{ res=stat.executeQuery("select * from inventory_barang_masuk"); 
 while (res.next()) { 
 t.addRow(new Object[]{ res.getString("Kd_Barang"),
 res.getString("Nama_Barang"), 
 res.getString("Tanggal_Masuk"),  
 res.getString("Jumlah"), 
 res.getString("Kondisi") 
 }); 
 }
 }catch (Exception e) { 
 JOptionPane.showMessageDialog(rootPane, e); 
 }
}

private void tabel2(){ 
DefaultTableModel t= new DefaultTableModel();
t.addColumn("Kode Barang"); 
t.addColumn("Nama Barang");
t.addColumn("Tanggal Masuk"); 
t.addColumn("Tanggal Keluar"); 
t.addColumn("Jumlah"); 
t.addColumn("Kondisi"); 
 tbl2.setModel(t); try{ res=stat.executeQuery("select * from inventory_barang_keluar"); 
 while (res.next()) { 
 t.addRow(new Object[]{ res.getString("Kd_Barang"),
 res.getString("Nama_Barang"),
 res.getString("Tanggal_Masuk"), 
 res.getString("Tanggal_Keluar"),  
 res.getString("Jumlah"), 
 res.getString("Kondisi") 
 }); 
 }
 }catch (Exception e) { 
 JOptionPane.showMessageDialog(rootPane, e); 
 }
}

private void kondisi(){ 
kondisi.addItem("Baik"); 
kondisi.addItem("Rusak Ringan");
kondisi.addItem("Rusak Berat"); 
kondisi.setSelectedIndex(-1); 
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nama = new javax.swing.JTextField();
        masuk = new javax.swing.JButton();
        clear = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        keluar = new javax.swing.JButton();
        edit = new javax.swing.JButton();
        kondisi = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl1 = new javax.swing.JTable();
        jumlah = new javax.swing.JTextField();
        kode = new javax.swing.JTextField();
        exit = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cari = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tglm = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl2 = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        tglk = new javax.swing.JTextField();
        hapus1 = new javax.swing.JButton();
        hapus2 = new javax.swing.JButton();
        label1 = new java.awt.Label();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMaximizedBounds(new java.awt.Rectangle(0, 0, 1190, 640));
        setMaximumSize(new java.awt.Dimension(0, 0));
        setMinimumSize(new java.awt.Dimension(1190, 640));
        setPreferredSize(new java.awt.Dimension(1190, 640));
        setSize(new java.awt.Dimension(0, 0));

        nama.setBackground(new java.awt.Color(204, 204, 255));
        nama.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        masuk.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        masuk.setText("Input Barang Masuk");
        masuk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                masukActionPerformed(evt);
            }
        });

        clear.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        clear.setText("Clear");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel4.setText("Nama Barang");

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel8.setText("Jumlah");

        keluar.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        keluar.setText("Input Barang Keluar");
        keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keluarActionPerformed(evt);
            }
        });

        edit.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        edit.setText("Update");
        edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editActionPerformed(evt);
            }
        });

        kondisi.setBackground(new java.awt.Color(204, 204, 255));
        kondisi.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        kondisi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Baik", "Rusak Ringan", "Rusak Berat" }));
        kondisi.setSelectedIndex(-1);

        tbl1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        tbl1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbl1);

        jumlah.setBackground(new java.awt.Color(204, 204, 255));
        jumlah.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        kode.setBackground(new java.awt.Color(204, 204, 255));
        kode.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        kode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kodeActionPerformed(evt);
            }
        });

        exit.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        exit.setText("Exit");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel5.setText("Tanggal Masuk");

        jLabel2.setBackground(new java.awt.Color(137, 167, 208));
        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("PROGRAM INVENTARIS ASET");

        cari.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        cari.setText("Search");
        cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cariActionPerformed(evt);
            }
        });

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel3.setText("Kode Barang");

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel7.setText("Kondisi");

        jPanel4.setBackground(new java.awt.Color(137, 167, 208));
        jPanel4.setPreferredSize(new java.awt.Dimension(598, 40));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Solusi terbaik bagi setiap pemilik bisnis, baik kecil maupun besar.");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(80, 80, 80))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        tglm.setBackground(new java.awt.Color(204, 204, 255));
        tglm.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        tbl2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        tbl2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl2MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl2);

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel9.setText("Tabel Barang Masuk");

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel10.setText("Tabel Barang Keluar");

        jLabel11.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel11.setText("Tanggal Keluar");

        tglk.setBackground(new java.awt.Color(204, 204, 255));
        tglk.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        hapus1.setBackground(new java.awt.Color(255, 51, 51));
        hapus1.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        hapus1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inventory_barang_image/Delete.png"))); // NOI18N
        hapus1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapus1ActionPerformed(evt);
            }
        });

        hapus2.setBackground(new java.awt.Color(255, 51, 51));
        hapus2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        hapus2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inventory_barang_image/Delete.png"))); // NOI18N
        hapus2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapus2ActionPerformed(evt);
            }
        });

        label1.setAlignment(java.awt.Label.CENTER);
        label1.setFont(new java.awt.Font("SansSerif", 2, 18)); // NOI18N
        label1.setText("Input / Review Barang");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 990, Short.MAX_VALUE)
                        .addGap(20, 20, 20))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(22, 22, 22)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                    .addComponent(kondisi, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                    .addComponent(masuk, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(hapus1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(keluar, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(hapus2, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabel11)
                                                        .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(tglm, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE)
                                                        .addComponent(tglk)
                                                        .addComponent(jumlah)))
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(cari)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(clear, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(edit)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(exit, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(50, 50, 50)
                                                        .addComponent(kode, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel4)
                                                .addGap(50, 50, 50)
                                                .addComponent(nama, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(105, 105, 105)
                                        .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(48, 48, 48)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(456, 456, 456)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 564, Short.MAX_VALUE))))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel2)
                .addGap(10, 10, 10)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(exit, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cari)
                    .addComponent(edit)
                    .addComponent(clear))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(kode, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tglm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tglk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jumlah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(kondisi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(masuk, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(keluar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(hapus1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(hapus2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void hapus2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapus2ActionPerformed
        int ok=JOptionPane.showConfirmDialog(null,"Apakah Anda Yakin Untuk Menghapus Data Ini???","Confirmation",JOptionPane.YES_NO_OPTION);
        try {
            stat.executeUpdate("delete from inventory_barang_keluar where "
                + "Kd_Barang='"+kode.getText()
                +"'" );

            kosongkan();
            JOptionPane.showMessageDialog(null, "Data Berhasil Di Hapus");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Perintah Salah : "+e);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_hapus2ActionPerformed

    private void hapus1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapus1ActionPerformed
        int ok=JOptionPane.showConfirmDialog(null,"Apakah Anda Yakin Untuk Menghapus Data Ini???","Confirmation",JOptionPane.YES_NO_OPTION);
        try {
            stat.executeUpdate("delete from inventory_barang_masuk where "
                + "Kd_Barang='"+kode.getText()
                +"'" );

            kosongkan();
            JOptionPane.showMessageDialog(null, "Data Berhasil Di Hapus");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Perintah Salah : "+e);
        }// TODO add your handling code here:
    }//GEN-LAST:event_hapus1ActionPerformed

    private void tbl2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl2MouseClicked
        int i = tbl2.getSelectedRow();
        if(i==-1){
            return;
        }
        String code = (String)tbl2.getValueAt(i,0);
        String code1 = (String)tbl2.getValueAt(i,1);
        String code2 = (String)tbl2.getValueAt(i,2);
        String code3 = (String)tbl2.getValueAt(i,3);
        String code4 = (String)tbl2.getValueAt(i,4);
        String code5 = (String)tbl2.getValueAt(i,5);
        kode.setText(code);
        nama.setText(code1);
        tglm.setText(code2);
        tglk.setText(code3);
        jumlah.setText(code4);
        kondisi.setSelectedItem(code5);    // TODO add your handling code here:
    }//GEN-LAST:event_tbl2MouseClicked

    private void cariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cariActionPerformed
        try {
            res=stat.executeQuery("select * from inventory_barang_masuk where "+ "Kd_Barang='" +kode.getText()
                +"'" ); while (res.next()) {
                nama.setText(res.getString("Nama_Barang"));
                tglm.setText(res.getString("Tanggal_Masuk"));
                jumlah.setText(res.getString("jumlah"));
                kondisi.setSelectedItem(res.getString("kondisi"));
            }
        }
        catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_cariActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        JOptionPane.showMessageDialog(null, "Anda Keluar");
        System.exit(0);         // TODO add your handling code here:
    }//GEN-LAST:event_exitActionPerformed

    private void kodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kodeActionPerformed
        try {
            res=stat.executeQuery("select * from inventory_barang_masuk where "+ "Kd_Barang='" +kode.getText()
                +"'" ); while (res.next()) {
                nama.setText(res.getString("Nama_Barang"));
                tglm.setText(res.getString("Tanggal_Masuk"));
                jumlah.setText(res.getString("Jumlah"));
                kondisi.setSelectedItem(res.getString("Kondisi"));
            }
        }
        catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }// TODO add your handling code here:
    }//GEN-LAST:event_kodeActionPerformed

    private void tbl1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl1MouseClicked
        int i = tbl1.getSelectedRow();
        if(i==-1){
            return;
        }
        String code = (String)tbl1.getValueAt(i,0);
        String code1 = (String)tbl1.getValueAt(i,1);
        String code2 = (String)tbl1.getValueAt(i,2);
        String code3 = (String)tbl1.getValueAt(i,3);
        String code4 = (String)tbl1.getValueAt(i,4);
        kode.setText(code);
        nama.setText(code1);
        tglm.setText(code2);
        jumlah.setText(code3);
        kondisi.setSelectedItem(code4);        // TODO add your handling code here:
    }//GEN-LAST:event_tbl1MouseClicked

    private void editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editActionPerformed
        int ok=JOptionPane.showConfirmDialog(null,"Apakah Anda Yakin Untuk Update Data Ini???","Confirmation",JOptionPane.YES_NO_OPTION);
        try
        {
            String sql="update inventory_barang_masuk set Kd_Barang=?,Nama_Barang=?,Tanggal_Masuk=?,Jumlah=?,Kondisi=? where Kd_Barang='"+kode.getText()+"'";
            PreparedStatement st=con.prepareStatement(sql);
            if(ok==0)
            {
                try
                {
                    st.setString(1,kode.getText());
                    st.setString(2,nama.getText());
                    st.setString(3,tglm.getText());
                    st.setString(4,jumlah.getText());
                    st.setString(5,(String)kondisi.getSelectedItem());
                    st.executeUpdate();
                    JOptionPane.showMessageDialog(null,"Update Data Berhasil");
                    new Inventory_Barang().setVisible(true);
                    dispose();
                }
                catch (Exception e)
                {
                    JOptionPane.showMessageDialog(null, "Update Data Gagal");
                }
            }
        }catch (Exception e){}        // TODO add your handling code here:
    }//GEN-LAST:event_editActionPerformed

    private void keluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keluarActionPerformed
        try {
            stat.executeUpdate("insert into inventory_barang_keluar values ("
                + "'" +  kode.getText()+"',"
                + "'" + nama.getText()+"',"
                + "'" + tglm.getText()+"',"
                + "'" + tglk.getText()+"',"
                + "'" + jumlah.getText()+ "',"
                + "'" + kondisi.getSelectedItem()+ "')");

            this.tbl1();
            this.tbl2();
            kosongkan();
            JOptionPane.showMessageDialog(null, "Data Berhasil Dikeluarkan");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Perintah Salah : "+e);
        }
        new Inventory_Barang().setVisible(true);
        dispose();        // TODO add your handling code here:
            
// TODO add your handling code here:
    }//GEN-LAST:event_keluarActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        kosongkan();        // TODO add your handling code here:
    }//GEN-LAST:event_clearActionPerformed

    private void masukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_masukActionPerformed
        try {
            stat.executeUpdate("insert into inventory_barang_masuk values ("
                + "'" +  kode.getText()+"',"
                + "'" + nama.getText()+"',"
                + "'" + tglm.getText()+"',"
                + "'" + jumlah.getText()+ "',"
                + "'" + kondisi.getSelectedItem()+ "')");

            kosongkan();
            JOptionPane.showMessageDialog(null, "Berhasil Menyimpan Data");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Perintah Salah : "+e);
        }
                new Inventory_Barang().setVisible(true);
        dispose();        // TODO add your handling code here:
    
        // TODO add your handling code here:
    }//GEN-LAST:event_masukActionPerformed

public void tbl1() {
    int a = 100;
    Object [][] data = new Object[a][8];
    try {
        int i = 0;
        while (res.next())
        {
        data [1][0]=res.getString("Kd_Barang");
        data [1][1]=res.getString("Nama_Barang");
        data [1][2]=res.getString("Tanggal_Masuk");
        data [1][3]=res.getString("Jumlah");
        data [1][4]=res.getString("Kondisi");
        i++;
        }
        String [] setJudul={"Kd_Barang","Nama_Barang","Tanggal_Masuk","Jumlah","Kondisi"};
        tbl1.setModel(new DefaultTableModel(data, setJudul));
        data = new Object[1][8];
    } catch (Exception e){
      System.out.println("Gagal Tampil"+e.toString());
}
}

public void tbl2() {
    int a = 100;
    Object [][] data = new Object[a][8];
    try {
        int i = 0;
        while (res.next())
        {
        data [1][0]=res.getString("Kd_Barang");
        data [1][1]=res.getString("Nama_Barang");
        data [1][2]=res.getString("Tanggal_Masuk");
        data [1][3]=res.getString("Tanggal_Keluar");
        data [1][4]=res.getString("Jumlah");
        data [1][5]=res.getString("Kondisi");
        i++;
        }
        String [] setJudul={"Kd_Barang","Nama_Barang","Tanggal_Masuk","Tanggal_Keluar","Jumlah","Kondisi"};
        tbl1.setModel(new DefaultTableModel(data, setJudul));
        data = new Object[1][8];
        } catch (Exception e){
      System.out.println("Gagal Tampil"+e.toString());
}
}

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inventory_Barang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inventory_Barang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inventory_Barang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inventory_Barang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inventory_Barang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cari;
    private javax.swing.JButton clear;
    private javax.swing.JButton edit;
    private javax.swing.JButton exit;
    private javax.swing.JButton hapus1;
    private javax.swing.JButton hapus2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jumlah;
    private javax.swing.JButton keluar;
    private javax.swing.JTextField kode;
    private javax.swing.JComboBox<String> kondisi;
    private java.awt.Label label1;
    private javax.swing.JButton masuk;
    private javax.swing.JTextField nama;
    private javax.swing.JTable tbl1;
    private javax.swing.JTable tbl2;
    private javax.swing.JTextField tglk;
    private javax.swing.JTextField tglm;
    // End of variables declaration//GEN-END:variables

    private Statement excuteUpdate(String total) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
